const PRICE_ACTION ='PRICE_ACTION';

const PRICE_DOOR ='PRICE_DOOR';
const PRICE_FLOOR ='PRICE_FLOOR';
const PRICE_PLINT ='PRICE_PLINT';
const PRICE_SILL ='PRICE_SILL';
const PRICE_LIGHT ='PRICE_LIGHT';
const PRICE_MOLDING ='PRICE_MOLDING';
const PRICE_ELECTRIC='PRICE_ELECTRIC';

const PRICE_SHOWER='PRICE_SHOWER';
const PRICE_KERAMAWALL='PRICE_KERAMAWALL';
const PRICE_TOILET='PRICE_TOILET';
const PRICE_LOCKER='PRICE_LOCKER';
const PRICE_BATHFLOOR='PRICE_BATHFLOOR';
const PRICE_BATH='PRICE_BATH';

const PRICE_KITCHEN = 'PRICE_KITCHEN';
const PRICE_APRON = 'PRICE_APRON';

export {PRICE_ACTION,
  PRICE_DOOR,PRICE_ELECTRIC,PRICE_FLOOR,PRICE_LIGHT,PRICE_MOLDING,PRICE_PLINT,PRICE_SILL,
  PRICE_BATH,PRICE_BATHFLOOR,PRICE_KERAMAWALL,PRICE_LOCKER,PRICE_SHOWER,PRICE_TOILET,
  PRICE_KITCHEN, PRICE_APRON}